services:
  db:
    image: mysql:8.0 # 컨테이너에서 사용하는 이미지
    container_name: luckyhankki-mysql # 컨테이너 이름
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: lucky_hankki
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"  # 포트 매핑 (로컬 포트:컨테이너 포트)
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s  # 헬스체크 간격
      timeout: 5s    # 각 ping 요청이 응답 없을 때까지 기다리는 최대 시간
      retries: 3     # 실패를 3번 반복하면 unhealthy로 간주
      start_period: 15s
    networks:
      - lucky-net

  backend:
    # 빌드 설정. 현재 디렉토리의 Dockerfile을 사용해 이미지 생성
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luckyhankki
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lucky_hankki?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - lucky-net

volumes:
  db-data:

networks:
  lucky-net:
    driver: bridge