spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    source:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${MYSQL_SOURCE_URL}
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
        read-only: false
    replica:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${MYSQL_REPLICA_URL}
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
        read-only: true
  sql:
    init:
      mode: always


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true


logging:
  level:
    org.hibernate.SQL: debug