spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    source:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${MYSQL_SOURCE_URL}
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
        read-only: false
    replica:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${MYSQL_REPLICA_URL}
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
        read-only: true
  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true

  jwt:
    secret: 4387a92f94766c7597a1d8d353f8514f0c120376ddd59110f64687e33e0f2981

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework:
      batch: debug
      batch.core: debug