services:
  db:
    image: mysql:9.3.0
    container_name: luckyhankki-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: lucky_hankki
    ports:
      - "13306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s  # 헬스체크 간격
      timeout: 5s    # 각 ping 요청이 응답 없을 때까지 기다리는 최대 시간
      retries: 3     # 실패를 3번 반복하면 unhealthy로 간주
      start_period: 15s

volumes:
  db-data: