@startuml
'일반 사용자 또는 판매자가 리뷰를 조회하는 시퀀스 다이어그램
actor Customer
actor Seller

participant ReviewService
participant ReviewRepository

alt 일반 사용자
    Customer -> ReviewService : 상품 리뷰 조회 요청
    ReviewService -> ReviewRepository : 상품 리뷰 조회
    ReviewRepository --> ReviewService : 가게 별점, 평가 수, 상위 3개 키워드
    ReviewService --> Customer : 상품 리뷰 조회 응답
else 판매자
    Seller -> ReviewService : 상품 리뷰 요청
    ReviewService -> ReviewRepository : 상품 리뷰 조회
    ReviewRepository --> ReviewService : 가게 별점, 평가 수, 각 키워드별 개수
    ReviewService --> Seller : 상품 리뷰 조회 응답
end

@enduml